version "3"

services:
    webmonster_docker:
        build: WebMonster/
        restart: always
        ports:
            - 8080:8080
        environment:
            - ipv4addr=172.18.96.1
    
    gobot_docker:
        build: GoBot/
        restart: always
        
    postgres:
        image: postgres
        restart: always
        ports:
            5432:5432
        environment:
            POSTGRES_PASSWORD="s6c89q4g"
            
    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379
        