version: "3.9"
services:
    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
      #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.lets-encrypt.acme.tlschallenge=true"
            - "--certificatesresolvers.lets-encrypt.acme.email=vladimirsachkov2003@gmail.com"
            - "--certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
        ports:
            - "443:443"
            - "8080:8080"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    webmonster_docker:
        build: WebMonster/
        restart: always
        environment:
            - ipv4addr=10.116.0.2
        labels:
            - traefik.enable=true
            - traefik.http.routers.webmonster_docker.rule=Host(`map`)
            - traefik.http.routers.webmonster_docker.tls=true
            - traefik.port=80
            - traefik.http.routers.webmonster_docker.tls.certresolver=myresolver
        ports:
            - "80:80"
    gobot_docker:
        build: GoBot/
        restart: always
        environment:
            - ipv4addr=10.116.0.2
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=s6c89q4g
    rediska:
        image: redis
        restart: always
        ports:
            - 6379:6379